metalions = {
    "ZN": {"Name": "Zinc", "SMILES": "[Zn+2]"},
    "FE2": {"Name": "Iron", "SMILES": "[Fe+2]"},
    "CO": {"Name": "Cobalt", "SMILES": "[Co+2]"},
    "NI": {"Name": "Nickel", "SMILES": "[Ni+2]"},
    "MN": {"Name": "Manganese", "SMILES": "[Mn+2]"},
    "CU": {"Name": "Copper", "SMILES": "[Cu+2]"},
    "MO": {"Name": "Molybdenum", "SMILES": "[Mo]"},
}
aa_map = {
    "CYS": "C",
    "ASP": "D",
    "SER": "S",
    "GLN": "Q",
    "LYS": "K",
    "ILE": "I",
    "PRO": "P",
    "THR": "T",
    "PHE": "F",
    "ASN": "N",
    "GLY": "G",
    "HIS": "H",
    "LEU": "L",
    "ARG": "R",
    "TRP": "W",
    "ALA": "A",
    "VAL": "V",
    "GLU": "E",
    "TYR": "Y",
    "MET": "M",
    "XXX": "X",
}

# I got the list from https:/github.com/haddocking/pdb-tools/issues/23. There can be missing residues
modified_aminoacids = {
    "2AS": "ASP",
    "3AH": "HIS",
    "5HP": "GLU",
    "ACL": "ARG",
    "AGM": "ARG",
    "AIB": "ALA",
    "ALM": "ALA",
    "ALO": "THR",
    "ALY": "LYS",
    "ARM": "ARG",
    "ASA": "ASP",
    "ASB": "ASP",
    "ASK": "ASP",
    "ASL": "ASP",
    "ASQ": "ASP",
    "AYA": "ALA",
    "BCS": "CYS",
    "BHD": "ASP",
    "BMT": "THR",
    "BNN": "ALA",
    "BUC": "CYS",
    "BUG": "LEU",
    "C5C": "CYS",
    "C6C": "CYS",
    "CAS": "CYS",
    "CCS": "CYS",
    "CEA": "CYS",
    "CGU": "GLU",
    "CHG": "ALA",
    "CLE": "LEU",
    "CME": "CYS",
    "CSD": "ALA",
    "CSO": "CYS",
    "CSP": "CYS",
    "CSS": "CYS",
    "CSW": "CYS",
    "CSX": "CYS",
    "CXM": "MET",
    "CY1": "CYS",
    "CY3": "CYS",
    "CYG": "CYS",
    "CYM": "CYS",
    "CYQ": "CYS",
    "DAH": "PHE",
    "DAL": "ALA",
    "DAR": "ARG",
    "DAS": "ASP",
    "DCY": "CYS",
    "DGL": "GLU",
    "DGN": "GLN",
    "DHA": "ALA",
    "DHI": "HIS",
    "DIL": "ILE",
    "DIV": "VAL",
    "DLE": "LEU",
    "DLY": "LYS",
    "DNP": "ALA",
    "DPN": "PHE",
    "DPR": "PRO",
    "DSN": "SER",
    "DSP": "ASP",
    "DTH": "THR",
    "DTR": "TRP",
    "DTY": "TYR",
    "DVA": "VAL",
    "EFC": "CYS",
    "FLA": "ALA",
    "FME": "MET",
    "GGL": "GLU",
    "GL3": "GLY",
    "GLZ": "GLY",
    "GMA": "GLU",
    "GSC": "GLY",
    "HAC": "ALA",
    "HAR": "ARG",
    "HIC": "HIS",
    "HIP": "HIS",
    "HMR": "ARG",
    "HPQ": "PHE",
    "HTR": "TRP",
    "HYP": "PRO",
    "IAS": "ASP",
    "IIL": "ILE",
    "IYR": "TYR",
    "KCX": "LYS",
    "LLP": "LYS",
    "LLY": "LYS",
    "LTR": "TRP",
    "LYM": "LYS",
    "LYZ": "LYS",
    "MAA": "ALA",
    "MEN": "ASN",
    "MHS": "HIS",
    "MIS": "SER",
    "MLE": "LEU",
    "MPQ": "GLY",
    "MSA": "GLY",
    "MSE": "MET",
    "MVA": "VAL",
    "NEM": "HIS",
    "NEP": "HIS",
    "NLE": "LEU",
    "NLN": "LEU",
    "NLP": "LEU",
    "NMC": "GLY",
    "OAS": "SER",
    "OCS": "CYS",
    "OMT": "MET",
    "PAQ": "TYR",
    "PCA": "GLU",
    "PEC": "CYS",
    "PHI": "PHE",
    "PHL": "PHE",
    "PR3": "CYS",
    "PRR": "ALA",
    "PTR": "TYR",
    "PYX": "CYS",
    "SAC": "SER",
    "SAR": "GLY",
    "SCH": "CYS",
    "SCS": "CYS",
    "SCY": "CYS",
    "SEL": "SER",
    "SEP": "SER",
    "SET": "SER",
    "SHC": "CYS",
    "SHR": "LYS",
    "SMC": "CYS",
    "SOC": "CYS",
    "STY": "TYR",
    "SVA": "SER",
    "TIH": "ALA",
    "TPL": "TRP",
    "TPO": "THR",
    "TPQ": "ALA",
    "TRG": "LYS",
    "TRO": "TRP",
    "TYB": "TYR",
    "TYI": "TYR",
    "TYQ": "TYR",
    "TYS": "TYR",
    "TYY": "TYR",
    "MLZ": "LYS",
    "M0H": "CYS",
    "KPI": "LYS",
    "ABA": "ALA",
    "OHI": "HIS",
    "DDE": "HIS",
    "LYX": "LYS",
    "CAF": "CYS",
    "CMH": "CYS",
    "1PA": "PHE",
    "A0A": "ASP",
    "NAL": "ALA",
    "HS8": "HIS",
    "SUI": "ASP",
    "MLY": "LYS",
    "NZH": "HIS",
    "SUN": "SER",
    "LA2": "LYS",
    "LED": "LEU",
    "MHO": "MET",
    "0A8": "CYS",
    "MDO": "ALA",
    "CSA": "CYS",
    "FVA": "VAL",
    "TYN": "TYR",
    "TRQ": "TRP",
    "NIY": "TYR",
    "FMT": "XXX",
    "ACE": "XXX",
    "4MM": "XXX",
    "48V": "XXX",
    "EXB": "XXX",
    "YCP": "XXX",
    "PYR": "XXX",
}

nucleotides = [
    "DC",
    "DG",
    "DA",
    "DT",
    "DU",
    "G",
    "C",
    "A",
    "T",
    "U",
    "64T",
    "5PY",
    "MA7",
    "6OG",
    "4PC",
    "DDG",
    "2DT",
    "GNE",
    "OMC",
    "TGP",
    "BRU",
]
